query AllPeopleQuery {
    allPeople {
        people {
            name
            homeworld {
                name
            }
            species {
                name
            }
            gender
            id
        }
    }
}
