query AllJudges($limit: Int, $page: Int) {
    judges(limit: $limit, page: $page) {
        id
        name
    }
}

query Judge($id: ID!) {
    judges_by_id(id: $id) {
        name
        id
    }
}
