query Stats {
    allFilms {
        totalCount
    }
    allPeople {
        totalCount
    }
    allPlanets {
        totalCount
    }
    allSpecies {
        totalCount
    }
    allStarships {
        totalCount
    }
    allVehicles {
        totalCount
    }
}
