query AboutPage {
    about_page {
        id
        title_bar_text

        heading

        enter_now_section_CTA_label

        enter_now_section_image {
            id
            filename_disk
            description
        }

        challenge_section_youtube_video_id
        challenge_section_heading
        challenge_section_body

        judges_section_heading
        judges_section_judge {
            id
            judge {
                id
                name
                company
                image {
                    id
                    filename_disk
                    description
                }
            }
        }
        judges_section_body
        judges_section_CTA_label

        brands_section_text

        multi_level_questions {
            id
            question {
                id
                title
                body {
                    id
                    multi_level_question_items {
                        id
                        level_1_title
                        level_2_title
                        level_2_subtext
                        level_3_text
                        level_3_links {
                            id
                            multi_level_question_item_links {
                                id
                                label
                                url
                            }
                        }
                    }
                }
            }
        }

        textarea_questions {
            id
            question {
                id
                title
                body
            }
        }
    }

    brands {
        id
        image {
            id
            description
            filename_disk
        }
    }
}
