query HomePage  ($limit: Int, $page: Int, $filterQuery: past_winners_filter)
 {
    home_page {
        id
        title_bar_text
        enter_now_section_heading
        enter_now_section_sub_heading
        enter_now_section_body
        enter_now_section_CTA_label
        hero_section_youtube_video_id
        hero_section_right_side_svg {
            id
            filename_disk
            description
        }
        innovator_section_heading
        innovator_section_body
        innovator_section_CTA_label
        innovator_section_image {
            id
            filename_disk
            description
        }
        brands_section_heading
        brands_section_description
        brands_section_CTA_label

        inspiration_articles {
            id
            inspiration_article {
                id
                title
                body
                read_more_label
                read_more_link
                image {
                    id
                    filename_disk
                    description
                }
            }
        }
    }

    past_winners_page {
        id
        heading
    }
    past_winners_categories {
        id
        category
    }
    past_winners_years {
        id
        year
    }
    past_winners(limit: $limit, page: $page, filter: $filterQuery) {
        id
        name
        image {
            id
            filename_disk
            description
        }
        short_description
        year {
            id
            past_winners_year {
                id
                year
            }
        }
        school_name
        students_name
        youtube_video_id
        project_information
        worksheets {
            id
            past_winners_worksheet {
                worksheet {
                    id
                    title
                    filename_disk
                }
            }
        }
        categories {
            id
            past_winners_category {
                id
                category
            }
        }
    }
}

