query InspirationPage($limit: Int, $page: Int) {
    inspiration_page {
        id
        heading
        description
        title_bar_text
        meta_description
        hero_image {
            id
            filename_disk
            description
            svg_code
        }
    }
    inspiration_articles_aggregated {
        count {
            id
        }
    }
    inspiration_articles(limit: $limit, page: $page, sort: ["sort", "date_created"]) {
        id
        image {
            id
            filename_disk
            description
            svg_code
        }
        title
        body
        read_more_label
        read_more_link
    }
}
