query InspirationPage($limit: Int, $page: Int) {
    inspiration_page {
        id
        heading
        description
        title_bar_text
        meta_description
        meta_keywords
        hero_image {
            id
            filename_disk
            description
        }
    }
    inspiration_articles_aggregated {
        count {
            id
        }
    }
    inspiration_articles(limit: $limit, page: $page) {
        id
        image {
            id
            filename_disk
            description
        }
        title
        body
        read_more_label
        read_more_link
    }
}
