query PastWinnersPage($limit: Int, $page: Int, $filterQuery: past_winners_filter) {
    past_winners_page {
        id
        heading
        title_bar_text
    }
    past_winners_categories {
        id
        category
    }
    past_winners_years {
        id
        year
    }
    past_winners(limit: $limit, page: $page, filter: $filterQuery, sort: ["sort", "date_created"]) {
        id
        name
        image {
            id
            filename_disk
            description
        }
        short_description
        year {
            id
            past_winners_year {
                id
                year
            }
        }
        school_name
        students_name
        youtube_video_id
        project_information
        worksheets {
            id
            past_winners_worksheet {
                id
                worksheet {
                    id
                    title
                    filename_disk
                }
            }
        }
        categories {
            id
            past_winners_category {
                id
                category
            }
        }
    }
}
