query pastWinnerDetails($id: ID!) {
    past_winners_by_id(id: $id) {
        id
        name
        students_name
        short_description
        youtube_video_id
        categories {
            id
            past_winners_category {
                id
                category
            }
        }
        school_name
        year {
            id
            past_winners_year {
                id
                year
            }
        }
        project_information
        worksheets {
            id
            past_winners_worksheet {
                id
                worksheet {
                    id
                    filename_disk
                    description
                }
            }
        }
    }
}
